# Generated by Django 6.0.2 on 2026-02-17 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('admin_sistema', 'Admin do Sistema'), ('admin_secundario', 'Admin Secundário'), ('funcionario', 'Funcionário'), ('cliente', 'Cliente')], max_length=20, unique=True, verbose_name='Tipo de Papel')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Papel',
                'verbose_name_plural': 'Papéis',
                'ordering': ['tipo'],
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo',
        ),
        migrations.CreateModel(
            name='UsuarioPapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Atribuição')),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.papel', verbose_name='Papel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário-Papel',
                'verbose_name_plural': 'Usuários-Papéis',
                'ordering': ['data_atribuicao'],
                'unique_together': {('usuario', 'papel')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='papeis',
            field=models.ManyToManyField(through='usuarios.UsuarioPapel', to='usuarios.papel', verbose_name='Papéis'),
        ),
    ]
