# Generated by Django 6.0.2 on 2026-02-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='quantidade_mesas',
            field=models.PositiveIntegerField(default=10, help_text='Número total de mesas (cada mesa comporta 4 pessoas)', verbose_name='Quantidade de Mesas'),
        ),
    ]
