# Generated by Django 6.0.2 on 2026-03-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_restaurante_quantidade_mesas'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='horario_funcionamento',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Horário de Funcionamento'),
        ),
    ]
