# Generated by Django 6.0.2 on 2026-02-20 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesas', '0002_remove_mesa_capacidade'),
        ('restaurantes', '0002_restaurante_quantidade_mesas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(verbose_name='Data da Reserva')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('quantidade_pessoas', models.PositiveIntegerField(verbose_name='Quantidade de Pessoas')),
                ('nome_cliente', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('telefone_cliente', models.CharField(max_length=20, verbose_name='Telefone do Cliente')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, verbose_name='Email do Cliente')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='restaurantes.restaurante', verbose_name='Restaurante')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário cadastrado que fez a reserva (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data_reserva', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='ReservaMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vinculacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Vinculação')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesas.mesa', verbose_name='Mesa')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Reserva-Mesa',
                'verbose_name_plural': 'Reservas-Mesas',
                'unique_together': {('reserva', 'mesa')},
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesas',
            field=models.ManyToManyField(related_name='reservas', through='reservas.ReservaMesa', to='mesas.mesa', verbose_name='Mesas'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['restaurante', 'data_reserva', 'horario'], name='reservas_re_restaur_e047d0_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['status'], name='reservas_re_status_d6e8b4_idx'),
        ),
    ]
